version: '3'
services:
  flutter-linux-image:
    image: ${LINUX_IMAGE}
    build:
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        ADDIONAL_LUNUX_IMAGE_PACKAGES: ${ADDIONAL_LUNUX_IMAGE_PACKAGES}
    tty: true
